= CalConnect Standard: VALARM Extensions for iCalendar

This work item belongs to CalConnect TC CALENDAR.

image:https://github.com/CalConnect/cc-valarm-extensions/workflows/generate/badge.svg["Build Status", link="https://github.com/CalConnect/cc-valarm-extensions/actions?workflow=generate"]

This document is available in its rendered forms here:

* https://calconnect.github.io/cc-valarm-extensions/[CalConnect: VALARM Extensions for iCalendar (HTML)]

== General

This document specifies the VALARM Extensions for iCalendar.

The document is published as the following:

* CalConnect CC 51017
* IETF draft-ietf-calext-valarm-extensions


== Fetching the document

[source,sh]
----
git clone https://github.com/CalConnect/cc-valarm-extensions/
----


== Installing build tools

See https://www.metanorma.com/author/topics/install/


== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker:

[source,sh]
----
docker run -v "$(pwd)":/metanorma -w /metanorma -it metanorma/mn metanorma site generate --agree-to-terms
----


== Building the document

[source,sh]
----
metanorma site generate --agree-to-terms
----

The generated documents are accessible under `_site/`.


== Iterating the document

[source,sh]
----
metanorma site generate --agree-to-terms
open _site/index.html
----


== License

Copyright its respective authors and CalConnect.
