[[ACKNOWLEDGED]]
== Alarm Acknowledgement

There is currently no way for a "VALARM" component to indicate whether it has
been triggered and acknowledged. With the advent of a standard client/server
protocol for calendaring and scheduling data (<<RFC4791>>) it is quite possible
for an event with an alarm to exist on multiple clients in addition to the
server. If each of those is responsible for performing the action when an alarm
triggers, then multiple "alerts" are generated by different devices. In such a
situation, a calendar user would like to be able to "dismiss" the alarm on one
device and have it automatically dismissed on the others too.

Also, with recurring events that have alarms, it is important to know when the
last alarm in the recurring set was acknowledged, so that the client can
determine whether past alarms have been missed.

To address these needs, this specification adds an "ACKNOWLEDGED" property to
"VALARM" components to indicate when the alarm was last sent or acknowledged.
This is defined by the syntax below.

[source%unnumbered]
----
alarmprop       /= *(

                   ; the following is OPTIONAL,
                   ; but MUST NOT occur more than once

                   acknowledged

                   )
----

=== Acknowledged Property

Property Name:: ACKNOWLEDGED

Purpose:: This property specifies the UTC date and time at which the
corresponding alarm was last sent or acknowledged.

Value Type:: DATE-TIME

Property Parameters:: IANA and non-standard property parameters can be specified
on this property.

Conformance:: This property can be specified within "VALARM" calendar
components.

Description:: This property is used to specify when an alarm was last sent or
acknowledged. This allows clients to determine when a pending alarm has been
acknowledged by a calendar user so that any alerts can be dismissed across
multiple devices. It also allows clients to track repeating alarms or alarms on
recurring events or to-dos to ensure that the right number of missed alarms can
be tracked.
+
Clients SHOULD set this property to the current date-time value in UTC when a
calendar user acknowledges a pending alarm. Certain kinds of alarm may not
provide feedback as to when the calendar user sees them, for example email based
alerts. For those kinds of alarms, the client SHOULD set this property when the
alarm is triggered and the action successfully carried out.
+
When an alarm is triggered on a client, clients can check to see if an
"ACKNOWLEDGED" property is present. If it is, and the value of that property is
greater than or equal to the computed trigger time for the alarm, then the
client SHOULD NOT trigger the alarm. Similarly, if an alarm has been triggered
and an "alert" presented to a calendar user, clients can monitor the iCalendar
data to determine whether an "ACKNOWLEDGED" property is added or changed in the
alarm component. If the value of any "ACKNOWLEDGED" property in the alarm
changes and is greater than or equal to the trigger time of the alarm, then
clients SHOULD dismiss or cancel any "alert" presented to the calendar user.

Format Definition:: This property is defined by the following notation:
+
[source%unnumbered]
----
acknowledged = "ACKNOWLEDGED" acknowledgedparam ":" datetime CRLF

acknowledgedparam  = *(

                     ; the following is OPTIONAL,
                     ; and MAY occur more than once

                     (";" other-param)

                     )
----

Example:: The following is an example of this property:
+
[source%unnumbered]
----
ACKNOWLEDGED:20090604T084500Z
----
